# 配置 plex 连接
auth:
  baseurl: "http://192.168.3.2:32400"
  token: "euN8BgiaA6iDMGsSSabg"

# 指定一个天数，比如 5 ，则脚本只会筛选 5 天内新添加的媒体。0 表示不筛选。
daysAgo: 0

# 是否开启排序标题转拼音首字母功能， true 开启，false 关闭
sortTitle: true
# 是否开启开启标签翻译功能， true 开启，false 关闭
transTags: true
# 读取标签翻译字典的文件路径，可以是一个网址url，也可以是一个本地文件路径
tagsFile: "https://mirror.ghproxy.com/raw.githubusercontent.com/sqkkyzx/plex_localization_zhcn/main/tags.yaml"

# 允许操作的库类型，设置 true 允许，false 禁用
allowLibs:
  movie:
    movie: true
    collection: true
  show:
    show: true
    collection: true
  artist:
    artist: true
    album: true
    track: true
    collection: true


# 允许操作的标签类型，设置 true 允许，false 禁用
allowTags:
  Genre: true
  Mood: true
  Style: true
  Country: true
  Director: false