# 配置 plex 连接
auth:
  baseurl: "http://192.168.3.2:32400"
  token: "euN8BgiaA6iDMGsSSabg"

playlist:
  - id: "top250"
    name: "top250"
  - id: "3151124"
    name: "1929-2024 美国奥斯卡金像奖最佳影片"
  - id: "3151122"
    name: "1946-2023 法国戛纳金棕榈奖最佳影片"
  - id: "157523791"
    name: "内地票房年度总排行：2024年电影/截至08.25"
  - id: "154245474"
    name: "内地票房年度总排行：2023年电影"
  - id: "113687305"
    name: "【实时更新】世界电影票房排行榜"